export const speakers = [
  {
    name: "Gaurav Gulati",
    role: "Group CIO, ",
    company: "Motherson Group",
    description: "",
    image: "gurugram/speakers/Gaurav-Gulati.png",
    linkedin: "#",
  },
  {
    name: "Parna Ghosh",
    role: "President, Group CIO and Data Protection Officer, ",
    company: "Uno Minda",
    description: "",
    image: "gurugram/speakers/Parna-Ghosh.png",
    linkedin: "#",
  },
  {
    name: "Supriya Kaul",
    role: "Regional IT CIO, ",
    company: "CNH Industrial",
    description: "",
    image: "gurugram/speakers/Supriya-Kaul.png",
    linkedin: "#",
  },
  {
    name: "Yogesh Kumar Sharma",
    role: "Chief Information Security Officer, ",
    company: "Jindal Stainless",
    description: "",
    image: "gurugram/speakers/Yogesh-Kumar-Sharma.png",
    linkedin: "#",
  },
  {
    name: "Sanjiv Jain",
    role: "Group Chief Information Officer, ",
    company: "Krishna Maruti Group",
    description: "",
    image: "gurugram/speakers/Sanjiv-Jain.png",
    linkedin: "#",
  },
  {
    name: "Vivek Madan",
    role: "Chief Technology Officer, ",
    company: "Hero Fincorp - Housing Entity",
    description: "",
    image: "gurugram/speakers/Vivek-Madan.png",
    linkedin: "#",
  },
  {
    name: "Arvind Heda",
    role: "Chief Technology Officer, ",
    company: "Info Edge India",
    description: "",
    image: "gurugram/speakers/Arvind-Heda.png",
    linkedin: "#",
  },
  {
    name: "Charit Agarwal",
    role: "Chief Data & AI Officer, ",
    company: "Niva Bupa Health Insurance",
    description: "",
    image: "gurugram/speakers/Charit-Agarwal.png",
    linkedin: "https://www.linkedin.com/in/charitagarwal/",
  },
  {
    name: "Ankit Gupta",
    role: "Chief Technology Officer, ",
    company: "PolicyBazaar for Business (PB Fintech Ltd.)",
    description: "",
    image: "gurugram/speakers/Ankit-Gupta.png",
    linkedin: "https://www.linkedin.com/in/ankitgupta871/",
  },
  {
    name: "Adish Jain",
    role: "Chief Security Officer, ",
    company: "PB Pay",
    description: "",
    image: "gurugram/speakers/Adish-Jain.png",
    linkedin: "https://www.linkedin.com/in/adishjain1995/",
  },
];
